[pytest]

# Test report
addopts = --html=report/reg.html --self-contained-html -n 4

# Retry failed tests
retries = 2

# Test discovery
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*